//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hranitel_PRO_WSR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Applications()
        {
            this.UsersGroupVisit = new HashSet<UsersGroupVisit>();
        }
    
        public int id { get; set; }
        public System.DateTime DateRegistration { get; set; }
        public int StatusCode { get; set; }
        public int AppointmentId { get; set; }
        public bool GroupVisit { get; set; }
        public Nullable<System.DateTime> StartSession { get; set; }
        public Nullable<System.DateTime> EndSession { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual StatusCode StatusCode1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersGroupVisit> UsersGroupVisit { get; set; }
    }
}
